#version: '3.8'
#
#services:
#  # MongoDB service
#  mongodb:
#    image: mongo:latest
#    container_name: mongodb_container
#    networks:
#      - mongo-network
#    ports:
#      - "27017:27017"
##    volumes:
##      - mongodb_data:/data/db
#
#
#  # Zookeeper service
#  zookeeper:
#    image: bitnami/zookeeper:latest
#    container_name: zookeeper
#    networks:
#      - kafka-network
#    ports:
#      - "2181:2181"
#    environment:
#      ALLOW_ANONYMOUS_LOGIN: "yes"
#
#  # Kafka service
#  kafka:
#    image: bitnami/kafka:latest
#    container_name: kafka
#    networks:
#      - kafka-network
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
#      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      ALLOW_PLAINTEXT_LISTENER: "yes"
#      KAFKA_CFG_NUM_PARTITIONS: 1
#      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 1
#      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1


#
#volumes:
#  mongodb_data:

#networks:
#  mongo-network:
#    driver: bridge
#  kafka-network:
#    driver: bridge



version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    networks:
      - app-network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Zookeeper service
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    networks:
      - app-network
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  # Kafka service
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    networks:
      - app-network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_NUM_PARTITIONS: 1
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1

  # Spring Boot Application
  spring-app:
    image: spring_iot_image
    container_name: spring_iot_container_app

    networks:
      - app-network
    depends_on:
      - mongodb
      - kafka
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/IOT_DB
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge

